"use client";
import { useEffect, useRef, useState } from "react";
const NUMBERS=Array.from({length:45},(_,i)=>i+1), TICKETS=100, WEEKS=52;
type Result={weeks:number; winningNumbers:number[]; winningTicket:number[]; ticketKind:"내 선택 번호"|"자동 번호"};
const ticket=()=>{const p=[...NUMBERS];for(let i=0;i<6;i++){const j=i+Math.floor(Math.random()*(p.length-i));[p[i],p[j]]=[p[j],p[i]]}return p.slice(0,6).sort((a,b)=>a-b)};
const key=(n:number[])=>n.join(",");
function Balls({numbers,win=false}:{numbers:number[];win?:boolean}){return <div className="balls" aria-label={`번호 ${numbers.join(", ")}`}>{numbers.map(n=><span key={n} className={`ball ball-${Math.ceil(n/10)}${win?" ball-win":""}`}>{n}</span>)}</div>}
export default function Home(){
 const [selected,setSelected]=useState<number[]>([]),[running,setRunning]=useState(false),[week,setWeek]=useState(0),[result,setResult]=useState<Result|null>(null);const cancel=useRef(false);
 useEffect(()=>()=>{cancel.current=true},[]);
 const toggle=(n:number)=>{if(running)return;setResult(null);setSelected(s=>s.includes(n)?s.filter(x=>x!==n):s.length===6?s:[...s,n].sort((a,b)=>a-b))};
 const simulate=async()=>{if(selected.length!==6||running)return;cancel.current=false;setRunning(true);setResult(null);setWeek(0);const mine=key(selected);let w=0;while(!cancel.current){for(let batch=0;batch<150&&!cancel.current;batch++){w++;const winning=ticket(),wk=key(winning),bought=new Set([mine]);if(mine===wk){setWeek(w);setResult({weeks:w,winningNumbers:winning,winningTicket:selected,ticketKind:"내 선택 번호"});setRunning(false);return}for(let i=1;i<TICKETS;i++){let auto=ticket(),ak=key(auto);while(bought.has(ak)){auto=ticket();ak=key(auto)}bought.add(ak);if(ak===wk){setWeek(w);setResult({weeks:w,winningNumbers:winning,winningTicket:auto,ticketKind:"자동 번호"});setRunning(false);return}}}setWeek(w);await new Promise<void>(r=>window.setTimeout(r,0))}setRunning(false)};
 const years=week?(week/WEEKS).toLocaleString("ko-KR",{maximumFractionDigits:1}):"0";
 return <main><section className="hero"><p className="eyebrow">LOTTO 6/45 · 100 TICKETS / WEEK</p><h1>언젠가는, <em>1등.</em></h1><p className="intro">내 번호 한 장과 자동 99장. 매주 100장씩 산다면 1등은 언제 찾아올까요?</p></section><section className="simulator"><div className="selection-panel"><div className="panel-heading"><div><p className="step">01 / 번호 선택</p><h2>당신의 행운 번호</h2></div><span className="count">{selected.length} <small>/ 6</small></span></div><p className="instruction">1부터 45 사이에서 숫자 여섯 개를 골라 주세요.</p><div className="number-grid" role="group" aria-label="로또 번호 선택">{NUMBERS.map(n=>{const on=selected.includes(n);return <button key={n} className={`number-button n-${Math.ceil(n/10)}${on?" selected":""}`} onClick={()=>toggle(n)} aria-pressed={on}>{n}</button>})}</div><div className="selection-footer"><div className="selected-numbers">{selected.length?<Balls numbers={selected}/>:<span>선택한 번호가 여기에 표시됩니다</span>}</div><button className="reset" onClick={()=>{setSelected([]);setResult(null)}} disabled={running||!selected.length}>초기화</button></div></div><aside className="status-panel" aria-live="polite"><p className="step">02 / 시뮬레이션</p>{!result?<><h2>{running?"행운을 찾는 중":"준비됐나요?"}</h2><p className="status-copy">{running?"매주 100장의 티켓으로 1등 번호를 기다리고 있습니다.":"번호를 모두 고르면, 1등이 나올 때까지 시간을 빠르게 돌립니다."}</p><div className="stat"><strong>{week.toLocaleString("ko-KR")}</strong><span>주차 진행 중 · 약 {years}년</span></div>{running?<button className="button secondary" onClick={()=>{cancel.current=true}}>시뮬레이션 멈추기</button>:<button className="button" onClick={simulate} disabled={selected.length!==6}>1등까지 시뮬레이션</button>}</>:<div className="result"><span className="jackpot">1등 당첨!</span><h2>{result.weeks.toLocaleString("ko-KR")}주 만의 만남</h2><p className="status-copy">약 <strong>{(result.weeks/WEEKS).toLocaleString("ko-KR",{maximumFractionDigits:1})}년</strong> 후, {result.ticketKind}이 1등에 당첨됐어요.</p><div className="result-card"><span>당첨 번호</span><Balls numbers={result.winningNumbers} win/></div><div className="result-card muted"><span>1등 티켓 · {result.ticketKind}</span><Balls numbers={result.winningTicket}/></div><button className="button" onClick={simulate}>다시 시뮬레이션</button></div>}</aside></section><section className="rules"><div><span>매주 구매</span><strong>선택 1장 + 자동 99장</strong></div><div><span>당첨 기준</span><strong>6개 번호 모두 일치</strong></div><div><span>알아둘 점</span><strong>실행할 때마다 결과가 달라져요</strong></div></section></main>
}